import React from 'react';
import SideBar from '../SideBar';

import { MdOutlineEditNote } from 'react-icons/md';
import { useDispatch, useSelector } from 'react-redux';
import { sidebarUiSlice, toggleSidebar } from './../../store/slices/sidebarUiSlice';
import Head  from 'next/head';


const ProfileLayout = ({ children }) => {

    const sidebar = useSelector(state => state.sidebarUiSlice.showSidebar);
    const dispatch = useDispatch();



    return (
        <div className='w-full relative'>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <button onClick={() => dispatch(toggleSidebar())} className={sidebar ? 'hidden' : 'w-10 h-10 p-2 shadow-xl rounded-r-lg bottom-1/2 bg-cyan-300 absolute'}>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8h9m-9 4h16m0 0-3-3m3 3-3 3M4 16h9" /></svg>
            </button>
            <div className={sidebar ? "bg-white md:w-1/2 lg:w-1/4 w-3/4 shadow-lg lg:block absolute" : 'hidden'}>
                <SideBar />
            </div>
            <div className='max-w-[1240px] mx-auto h-screen'>

                <div className='grid lg:grid-cols-3 py-6 '>

                    <div className="col-span-3 grid md:grid-cols-3 gap-4  px-2 md:px-6">
                        {children}
                    </div>
                </div>
            </div>
        </div>
    );
}

export default ProfileLayout;
